### ISSUE TITLE
Why is some content under the OGL? can it be licensed under CC-BY too?

### ISSUE THREAD

**Issue by Ferk** [Sagelt/Dungeon-World#194]
I see that the [LICENSE](https://github.com/Sagelt/Dungeon-World/blob/master/LICENSE) outlines some monsters and spells as "open game content", which seems to relate to the OGL 1.0a license.

Seeing how with the recent news from WotC, the future of this license is uncertain (and regardless of the end result, the trust on it has been affected), I was wondering if there's a specific reason why that content was licensed differently from the rest of the document.

I don't know if maybe some monsters might have been "inspired" by existing OGL content, but a lot of it seems pretty common / general monsters or spells. I wonder whether it'd be possible to relicense some of them to CC-BY, or at least replace some of the more dubious ones with alternatives.

https://github.com/Sagelt/Dungeon-World/blob/4396069d1a154c59627f0a142b84274eddf50c92/LICENSE#L3-L119

**Comment by Sagelt** [comment]
The OGL notice was added later based on feedback and was more of a precaution than anything since they share basically nothing with the OGL versions. To be cautious, I think the best option is to just change names where used. I'll try to work on that soon.
