### ISSUE TITLE
"Advanced Delving" refers to GM Principles that don't exist

### ISSUE THREAD

**Issue by NerdyNathan** [Sagelt/Dungeon-World#195]
The following are referred to as GM principles in "Advanced Delving" but are not found in the list of GM Principles in "GM"
- Make your move, but misdirect
- Give them something to work towards
- Sometimes, let them decide

I would open a pull request, but I'm not sure if these should be removed or replaced.

**Comment by Sagelt** [comment]
Yep, these are all old phrasings or AW principles that made it past early editing. Given that they're self-descriptive anyway and the text is very old at this point I don't think it's worth rewording, but something to be on the lookout for if we ever do significant updates.
